version: '3'

services:
  web:
    build: .
    image: hanneskimara/parking_detection
    command: python main.py
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
